name: Release @latest

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to bump (if you choose custom, please include it under custom version)
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
          - "custom"
      custom_version:
        description: The custom version to bump to (only for "custom" type)
        required: false
        type: string
        default: ""
      dryrun:
        type: boolean
        description: Dry-Run
permissions:
  contents: write
  id-token: write
jobs:
  # TODO: Test before releasing to ensure we don't release a broken version

  release:
    name: "Bump Score-storm: ${{ inputs.version }} version (${{ inputs.custom_version || 'n/a' }} custom version)"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # needs: [build_and_test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # Trusted publishing requires npm CLI >= 11.5.1
      - name: Ensure npm CLI supports OIDC
        run: |
          npm install -g npm@latest
          node --version
          npm --version

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.5
          run_install: false

      - name: Run pnpm install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run all workspace TSC builds
        run: pnpm run build

      - name: Setup git user
        run: |
          git config --global user.name "Dzmitry Dzehtsiarou"
          git config --global user.email "deemaagog@gmail.com"

      - name: Lerna Version (build query)
        shell: bash
        run: |
          if ${{inputs.dryrun == true && inputs.version != 'custom'}}
          then
              echo "LERNA_VERSION_TYPE=🧪 Dry-Run Auto" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version ${{ github.event.inputs.version }} --force-publish --yes  --dry-run" >> $GITHUB_ENV
          elif ${{inputs.dryrun == true && inputs.version == 'custom' && inputs.custom_version != ''}}
          then
              echo "LERNA_VERSION_TYPE=🧪 Dry-Run Custom" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version ${{ github.event.inputs.custom_version }} --force-publish  --yes --dry-run" >> $GITHUB_ENV
          elif ${{inputs.dryrun != true  && inputs.version != 'custom'}}
          then
              echo "LERNA_VERSION_TYPE=🚀 Prod Version Auto" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version ${{ github.event.inputs.version }} --force-publish --yes" >> $GITHUB_ENV
          elif ${{inputs.dryrun != true && inputs.version == 'custom' && inputs.custom_version != ''}}
          then
              echo "LERNA_VERSION_TYPE=🚀 Prod Version Custom" >> $GITHUB_ENV
              echo "LERNA_VERSION_QUERY=lerna version ${{ github.event.inputs.custom_version }} --force-publish  --yes" >> $GITHUB_ENV
          fi

      - name: Bump version
        run: pnpm exec ${{ env.LERNA_VERSION_QUERY }}
        env:
          GIT_USER: "deemaagog@gmail.com:${{ github.token }}"
          GH_TOKEN: ${{ github.token }}

      - name: Publish packages
        if: ${{ inputs.dryrun != true }}
        run: pnpm exec lerna publish from-package --yes
        env:
          GIT_USER: "deemaagog@gmail.com:${{ github.token }}"
          GH_TOKEN: ${{ github.token }}
